# Generated by Django 2.2.1 on 2019-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeepoints_id', models.IntegerField()),
                ('pointsattained', models.CharField(max_length=30)),
            ],
        ),
    ]
