# Generated by Django 2.2.1 on 2019-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='seniority',
            field=models.CharField(default='A', max_length=30),
        ),
        migrations.AddField(
            model_name='points',
            name='tenure',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
