# Generated by Django 2.2.1 on 2019-05-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_points_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='password',
            new_name='passwordz',
        ),
    ]
